### PR TITLE
Update for umpdc.dll and xmlite.dll

### PR DESCRIPTION
**Pull request by Kucharskov**
Hello!

I love that project which helps me a lot during checking malicious activity for RT actions. Last time i confirmed 2 new built-in exe files used for DLL Sideloading and i just want to update your database!

Please verify and correct my changes if needed. I always have problem with contributing with big projects ;)

Have a nice day!

### CODE REVIEW

**Comment by Kucharskov** [comment]
@wietze could you look at this and make an review?

**Review by Kucharskov — COMMENTED** [review]
Nice by adding me in Acknowledgements

**Comment by wietze** [comment]
image
image
Can confirm they work as expected ✅

**Review by wietze — APPROVED** [review]
Thank you for your contribution

**Pull request merged**
